# Generated by Django 2.0.5 on 2018-06-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
