# Generated by Django 2.0.5 on 2018-06-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180603_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='predected',
            field=models.IntegerField(null=True),
        ),
    ]
