# Generated by Django 2.0.5 on 2018-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectfeature_predected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfeature',
            name='backers',
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='usd_pledged',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
