# Generated by Django 2.0.5 on 2018-06-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180607_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfeature',
            old_name='DT_predected',
            new_name='DT_predicted',
        ),
        migrations.RenameField(
            model_name='projectfeature',
            old_name='RF_predected',
            new_name='RF_predicted',
        ),
    ]
