# Generated by Django 2.0.5 on 2018-06-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180607_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
